name = "Create Combined"
author = "alec"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94571121d65cdc7297e9cc5c983368feb511dce7a5332558d00488be6930b2fc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"

[options]
acceptable-game-versions = ["1.21"]
