name = "Create Combined"
author = "alec"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf5cf6be11a329496747fca22303026548c04ae1b098082b2705bcc82acd4bd4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"

[options]
acceptable-game-versions = ["1.21"]
