name = "Create Combined"
author = "alec"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8527a03ec8317130168486f565202f7dc17e7cb07879b668d451a9f7c6a6c01"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"

[options]
acceptable-game-versions = ["1.21"]
